language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - SURGE_LOGIN=nickkeane23@gmail.com
  - SURGE_TOKEN=281bf4bff0b9c5c0919bcdd30a0124c0
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  cleanup: false
  domain: nickkeane23-react-cargarage.surge.sh
  project: ./build/
on:
  branch: main